In [1]:
import pandas as pd

In [ ]:
pd.DataFrame({"YES": [50,20], "NO":[20,5]})  #defined as a python dict, containing lists for the values

   YES  NO
0   50  20
1   20   5

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},   #we can also assign labels/indexes
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [ ]:
pd.Series([1,2,"hi"])  #while df is a table, series is a list, can assigsn indexes like above but now also a name

0     1
1     2
2    hi
dtype: object